[#23] Adding dependency guard

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -45,64 +45,65 @@ jobs:
       - name: Check build-logic
         run: ./gradlew :build-logic:convention:check
 
-#      - name: Check spotless
-#        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache
+      #      - name: Check spotless
+      #        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache
 
-#      - name: Check Dependency Guard
-#        id: dependencyguard_verify
-#        continue-on-error: true
-#        run: ./gradlew dependencyGuard
+      - name: Check Dependency Guard
+        id: dependencyguard_verify
+        continue-on-error: true
+        run: ./gradlew dependencyGuard
 
-#      - name: Prevent updating Dependency Guard baselines if this is a fork
-#        id: checkfork_dependencyguard
-#        continue-on-error: false
-#        if: steps.dependencyguard_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
-#        run: |
-#          echo "::error::Dependency Guard failed, please update baselines with: ./gradlew dependencyGuardBaseline" && exit 1
+      - name: Prevent updating Dependency Guard baselines if this is a fork
+        id: checkfork_dependencyguard
+        continue-on-error: false
+        if: steps.dependencyguard_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Dependency Guard failed, please update baselines with: ./gradlew dependencyGuardBaseline" && exit 1
 
         # Runs if previous job failed
-#      - name: Generate new Dependency Guard baselines if verification failed and it's a PR
-#        id: dependencyguard_baseline
-#        if: steps.dependencyguard_verify.outcome == 'failure' && github.event_name == 'pull_request'
-#        run: |
-#          ./gradlew dependencyGuardBaseline
+      - name: Generate new Dependency Guard baselines if verification failed and it's a PR
+        id: dependencyguard_baseline
+        if: steps.dependencyguard_verify.outcome == 'failure' && github.event_name == 'pull_request'
+        run: |
+          ./gradlew dependencyGuardBaseline
 
-#      - name: Push new Dependency Guard baselines if available
-#        uses: stefanzweifel/git-auto-commit-action@v5
-#        if: steps.dependencyguard_baseline.outcome == 'success'
-#        with:
-#          file_pattern: '**/dependencies/*.txt'
-#          disable_globbing: true
-#          commit_message: "🤖 Updates baselines for Dependency Guard"
+      - name: Push new Dependency Guard baselines if available
+        uses: stefanzweifel/git-auto-commit-action@v5
+        if: steps.dependencyguard_baseline.outcome == 'success'
+        with:
+          file_pattern: '**/dependencies/*.txt'
+          disable_globbing: true
+          commit_message: "🤖 Updates baselines for Dependency Guard"
 
-#      - name: Run all local screenshot tests (Roborazzi)
-#        id: screenshotsverify
-#        continue-on-error: true
-#        run: ./gradlew verifyRoborazziDemoDebug
 
-#      - name: Prevent pushing new screenshots if this is a fork
-#        id: checkfork_screenshots
-#        continue-on-error: false
-#        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
-#        run: |
-#          echo "::error::Screenshot tests failed, please create a PR in your fork first."
-#          echo "Your fork's CI will take screenshots for your fork."
-#          exit 1
+      #      - name: Run all local screenshot tests (Roborazzi)
+      #        id: screenshotsverify
+      #        continue-on-error: true
+      #        run: ./gradlew verifyRoborazziDemoDebug
+
+      #      - name: Prevent pushing new screenshots if this is a fork
+      #        id: checkfork_screenshots
+      #        continue-on-error: false
+      #        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+      #        run: |
+      #          echo "::error::Screenshot tests failed, please create a PR in your fork first."
+      #          echo "Your fork's CI will take screenshots for your fork."
+      #          exit 1
 
       # Runs if previous job failed
-#      - name: Generate new screenshots if verification failed and it's a PR
-#        id: screenshotsrecord
-#        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
-#        run: |
-#          ./gradlew recordRoborazziDemoDebug
+      #      - name: Generate new screenshots if verification failed and it's a PR
+      #        id: screenshotsrecord
+      #        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
+      #        run: |
+      #          ./gradlew recordRoborazziDemoDebug
 
-#      - name: Push new screenshots if available
-#        uses: stefanzweifel/git-auto-commit-action@v5
-#        if: steps.screenshotsrecord.outcome == 'success'
-#        with:
-#          file_pattern: '*/*.png'
-#          disable_globbing: true
-#          commit_message: "🤖 Updates screenshots"
+      #      - name: Push new screenshots if available
+      #        uses: stefanzweifel/git-auto-commit-action@v5
+      #        if: steps.screenshotsrecord.outcome == 'success'
+      #        with:
+      #          file_pattern: '*/*.png'
+      #          disable_globbing: true
+      #          commit_message: "🤖 Updates screenshots"
 
       # Run local tests after screenshot tests to avoid wrong UP-TO-DATE. TODO: Ignore screenshots.
       - name: Run local tests
@@ -124,12 +125,12 @@ jobs:
           name: local-test-results
           path: '**/build/test-results/test*UnitTest/**.xml'
 
-#      - name: Upload screenshot results (PNG)
-#        if: ${{ !cancelled() }}
-#        uses: actions/upload-artifact@v4
-#        with:
-#          name: screenshot-test-results
-#          path: '**/build/outputs/roborazzi/*_compare.png'
+      #      - name: Upload screenshot results (PNG)
+      #        if: ${{ !cancelled() }}
+      #        uses: actions/upload-artifact@v4
+      #        with:
+      #          name: screenshot-test-results
+      #          path: '**/build/outputs/roborazzi/*_compare.png'
 
       - name: Check lint
         run: ./gradlew lintKotlin lint
@@ -155,7 +156,7 @@ jobs:
     timeout-minutes: 55
     strategy:
       matrix:
-        api-level: [26, 34]
+        api-level: [ 26, 34 ]
 
     steps:
       - name: Delete unnecessary tools 🔧
@@ -207,15 +208,15 @@ jobs:
           heap-size: 600M
           script: ./gradlew connectedDevelopDebugAndroidTest --daemon
 
-#      - name: Run local tests (including Roborazzi) for the combined coverage report (only API 30)
-#        if: matrix.api-level == 30
-#        # There is no need to verify Roborazzi tests to generate coverage.
-#        run: ./gradlew testDemoDebugUnitTest -Proborazzi.test.verify=false # Add Prod if we ever add JVM tests for prod
+      #      - name: Run local tests (including Roborazzi) for the combined coverage report (only API 30)
+      #        if: matrix.api-level == 30
+      #        # There is no need to verify Roborazzi tests to generate coverage.
+      #        run: ./gradlew testDemoDebugUnitTest -Proborazzi.test.verify=false # Add Prod if we ever add JVM tests for prod
 
       # Add `createProdDebugUnitTestCoverageReport` if we ever add JVM tests for prod
-#      - name: Generate coverage reports for Debug variants (only API 30)
-#        if: matrix.api-level == 30
-#        run: ./gradlew createDemoDebugCombinedCoverageReport
+      #      - name: Generate coverage reports for Debug variants (only API 30)
+      #        if: matrix.api-level == 30
+      #        run: ./gradlew createDemoDebugCombinedCoverageReport
 
       - name: Upload test reports
         if: ${{ !cancelled() }}
